### ISSUE TITLE
PlantName

### ISSUE THREAD

**Issue by marcelmiersebach** [dmslabsbr/hoymiles#157]
Hi I tried to get the addon running but I get this error Message in Home Assistent:

`2024-07-15 11:26:03.694 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/44349f66_hoymiles_solardata_edge/stats - Container addon_44349f66_hoymiles_solardata_edge is not running`

And this one in the "HoyMiles Solar Gateway Edge Addon" Debug Logs:

I guess there is an issue with the HOYMILES_PLANT_ID:
I used the Plant Name is this correct or should I use something else ?
I am not sure where to find the correct ID:

I am using: 

- HMS-800W-2T
- Home Assistant Green

Core
2024.7.2
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

Starting add-on container...
Mon Jul 15 11:32:22 CEST 2024
total 24
drwxr-xr-x    5 root     root          4096 Jul 15 11:32 .
drwxr-xr-x    1 root     root          4096 Jul 15 11:32 ..
drwxr-xr-x    2 root     root          4096 Jul 15 11:20 __pycache__
drwxr-xr-x    2 root     root          4096 Jul 15 11:28 jsons
-rw-------    1 root     root           606 Jul 15 11:32 options.json
drwxr-xr-x    2 root     root          4096 Jul 15 11:20 templates
[11:32:23] INFO: /data/secrets.ini not exists!
Getting mqtt data...
[11:32:26] INFO: null
[11:32:26] INFO: {"supervisor":"2024.06.2","homeassistant":"2024.7.2","hassos":"12.4","docker":"26.1.4","hostname":"homeassistant","operating_system":"Home Assistant OS 12.4","features":["reboot","shutdown","services","network","hostname","timedate","os_agent","haos","resolved","journal","disk","mount"],"machine":"green","arch":"aarch64","state":"running","supported_arch":["aarch64","armv7","armhf"],"supported":true,"channel":"stable","logging":"info","timezone":"Europe/Vienna"}
[11:32:26] INFO: {"supervisor":"2024.06.2","homeassistant":"2024.7.2","hassos":"12.4","docker":"26.1.4","hostname":"homeassistant","operating_system":"Home Assistant OS 12.4","features":["reboot","shutdown","services","network","hostname","timedate","os_agent","haos","resolved","journal","disk","mount"],"machine":"green","arch":"aarch64","state":"running","supported_arch":["aarch64","armv7","armhf"],"supported":true,"channel":"stable","logging":"info","timezone":"Europe/Vienna"}
dmslabs - Home Assistant HoyMiles Solar Data Gateway Add-on
2024-07-15 11:32:27,777 - HoymilesAdd-on - INFO - ********** dmslabs&Cosik Hoymiles Gateway  v.1.3.0
2024-07-15 11:32:27,778 - HoymilesAdd-on - INFO - Starting up... 2024-07-15 11:32:27
2024-07-15 11:32:27,780 - HoymilesAdd-on - INFO - Using Internal MQTT Server: core-mosquitto
2024-07-15 11:32:27,780 - HoymilesAdd-on - INFO - Using Internal MQTT User: addons
2024-07-15 11:32:27,781 - HoymilesAdd-on.mqttapi.Mqtt - INFO - mqtt.Client 26a23618-428d-11ef-b3b1-20f83b006e73
2024-07-15 11:32:27,782 - HoymilesAdd-on.mqttapi.Mqtt - INFO - Starting MQTT core-mosquitto
2024-07-15 11:32:27,782 - HoymilesAdd-on.mqttapi.Mqtt - DEBUG - SSL: OpenSSL 1.1.1o  3 May 2022
2024-07-15 11:32:27,783 - HoymilesAdd-on.mqttapi.Mqtt - DEBUG - mqttStart TLS: False
2024-07-15 11:32:27,783 - HoymilesAdd-on.mqttapi.Mqtt - DEBUG - mqttStart MQTT_USERNAME: addons
2024-07-15 11:32:27,784 - HoymilesAdd-on.mqttapi.Mqtt - DEBUG - mqttStart MQTT_PASSWORD: xxxx
2024-07-15 11:32:27,784 - HoymilesAdd-on.mqttapi.Mqtt - DEBUG - mqttStart MQTT_PORT: 1883
2024-07-15 11:32:28,452 - HoymilesAdd-on.mqttapi.Mqtt - INFO - MQTT connected with result code 0
2024-07-15 11:32:28,452 - HoymilesAdd-on.mqttapi.Mqtt - INFO - Connected to core-mosquitto
Traceback (most recent call last):
  File "/hoymiles.py", line 499, in <module>
    sys.exit(main())  # next section explains the use of sys.exit
  File "/hoymiles.py", line 420, in main
    if int(id) < 100:
ValueError: invalid literal for int() with base 10: 'PlantName'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by marcelmiersebach** [comment]
solved it found the ID in the browser address bar.
sorry
