### ISSUE TITLE
Issue with wrong return types by code

### ISSUE THREAD

**Issue by focabr** [dmslabsbr/hoymiles#164]
Hi,

I'm having some problems with my internet, which is causing the addon to crash, see some logs below:

## Problem 2024-07-03
```
2024-07-03 18:57:34,348 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 18:57:34,869 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 18:57:36,355 - HoymilesAdd-on - INFO - Solar data publication...2024-07-03 18:57:36.355386
2024-07-03 18:57:36,355 - HoymilesAdd-on - INFO - _4796480 data publication...2024-07-03 18:57:36.355895
2024-07-03 18:57:36,365 - HoymilesAdd-on - INFO - DTU-Lite-S_1430210 data publication...2024-07-03 18:57:36.365301
2024-07-03 18:57:36,365 - HoymilesAdd-on - INFO - HMS-2000DW-4T_15430390 data publication...2024-07-03 18:57:36.365697
2024-07-03 18:57:36,365 - HoymilesAdd-on - INFO - HMS-2000-4T_6554090 data publication...2024-07-03 18:57:36.365904
2024-07-03 18:57:36,366 - HoymilesAdd-on - INFO - HMS-2000-4T_6554080 data publication...2024-07-03 18:57:36.366108
2024-07-03 18:57:36,366 - HoymilesAdd-on - INFO - HMS-2000-4T_6554110 data publication...2024-07-03 18:57:36.366572
2024-07-03 18:57:36,366 - HoymilesAdd-on - INFO - HMS-2000-4T_6554100 data publication...2024-07-03 18:57:36.366827
2024-07-03 19:05:36,368 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_of_tree
2024-07-03 19:05:37,089 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_count_station_real_data
2024-07-03 19:05:38,628 - HoymilesAdd-on.hoymilesapi.Hoymiles - WARNING - real_power = 0
2024-07-03 19:05:38,628 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - last_data_time 2024-07-03T18:48:43-03:00
2024-07-03 19:05:38,628 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 19:05:40,334 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 19:05:40,852 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 19:05:42,413 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 19:05:42,929 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-03 19:05:44,411 - HoymilesAdd-on - INFO - Solar data publication...2024-07-03 19:05:44.411413
2024-07-03 19:05:44,411 - HoymilesAdd-on - INFO - _4796480 data publication...2024-07-03 19:05:44.411952
2024-07-03 19:05:44,412 - HoymilesAdd-on - INFO - DTU-Lite-S_1430210 data publication...2024-07-03 19:05:44.412645
2024-07-03 19:05:44,413 - HoymilesAdd-on - INFO - HMS-2000DW-4T_15430390 data publication...2024-07-03 19:05:44.413285
2024-07-03 19:05:44,413 - HoymilesAdd-on - INFO - HMS-2000-4T_6554090 data publication...2024-07-03 19:05:44.413540
2024-07-03 19:05:44,414 - HoymilesAdd-on - INFO - HMS-2000-4T_6554080 data publication...2024-07-03 19:05:44.414446
2024-07-03 19:05:44,415 - HoymilesAdd-on - INFO - HMS-2000-4T_6554110 data publication...2024-07-03 19:05:44.415646
2024-07-03 19:05:44,415 - HoymilesAdd-on - INFO - HMS-2000-4T_6554100 data publication...2024-07-03 19:05:44.415873
2024-07-03 19:13:44,417 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_of_tree
2024-07-03 19:13:46,203 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_count_station_real_data
2024-07-03 19:14:32,163 - HoymilesAdd-on.hoymilesapi.Hoymiles - ERROR - Access error: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_count_station_real_data
2024-07-03 19:14:32,163 - HoymilesAdd-on.hoymilesapi.Hoymiles - ERROR - Status code: 502Bad Gateway
Exception in thread publicate_data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/hoymiles.py", line 341, in run
    self.execute(*self.args, **self.kwargs)
  File "/hoymiles.py", line 263, in publicate_data
    hoymiles_h.get_solar_data()
  File "/hoymilesapi.py", line 248, in get_solar_data
    status, self.solar_data = self.request_solar_data()
  File "/hoymilesapi.py", line 364, in request_solar_data
    if "status" in solar.keys():
AttributeError: 'str' object has no attribute 'keys'

```

## Problem 2024-07-05
```
2024-07-05 00:06:59,428 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-05 00:07:01,256 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-05 00:07:02,737 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-05 00:07:04,218 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-05 00:07:05,731 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_find_details
2024-07-05 00:07:07,357 - HoymilesAdd-on - INFO - Solar data publication...2024-07-05 00:07:07.357431
2024-07-05 00:07:07,357 - HoymilesAdd-on - INFO - _4796480 data publication...2024-07-05 00:07:07.357781
2024-07-05 00:07:07,358 - HoymilesAdd-on - INFO - DTU-Lite-S_1430210 data publication...2024-07-05 00:07:07.357992
2024-07-05 00:07:07,358 - HoymilesAdd-on - INFO - HMS-2000DW-4T_15430390 data publication...2024-07-05 00:07:07.358253
2024-07-05 00:07:07,358 - HoymilesAdd-on - INFO - HMS-2000-4T_6554090 data publication...2024-07-05 00:07:07.358397
2024-07-05 00:07:07,358 - HoymilesAdd-on - INFO - HMS-2000-4T_6554080 data publication...2024-07-05 00:07:07.358586
2024-07-05 00:07:07,358 - HoymilesAdd-on - INFO - HMS-2000-4T_6554110 data publication...2024-07-05 00:07:07.358859
2024-07-05 00:07:07,359 - HoymilesAdd-on - INFO - HMS-2000-4T_6554100 data publication...2024-07-05 00:07:07.359212
2024-07-05 00:15:07,360 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_of_tree
2024-07-05 00:15:08,931 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_count_station_real_data
2024-07-05 00:15:15,087 - HoymilesAdd-on.hoymilesapi.Hoymiles - ERROR - Access error: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_count_station_real_data
2024-07-05 00:15:15,087 - HoymilesAdd-on.hoymilesapi.Hoymiles - ERROR - Status code: 502Bad Gateway
Exception in thread publicate_data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/hoymiles.py", line 341, in run
    self.execute(*self.args, **self.kwargs)
  File "/hoymiles.py", line 263, in publicate_data
    hoymiles_h.get_solar_data()
  File "/hoymilesapi.py", line 248, in get_solar_data
    status, self.solar_data = self.request_solar_data()
  File "/hoymilesapi.py", line 364, in request_solar_data
    if "status" in solar.keys():
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by focabr** [comment]
Thx,

Problem solve.
