### ISSUE TITLE
Erro ao acessar - I can’t connect - 400 Bad request

### ISSUE THREAD

**Issue by tonwelle** [dmslabsbr/hoymiles#23]
Hi,
when trying to access my hoymiles plant, the Home Assistant addon (running in Hassio) is running in an error.
After getting the Token (according to the log) it tries to connect to the actual data api and fails with a 400 bad request.

Login data is correct, alas I am not shure about the „Plant ID“. I’ve tried 00 and 01 and various combinations of my device IDs and serials.
Do you know how I can find the correct plant ID?
And is the Bad Request error related to the ID or another problem?

I’ve attached part of the log below. 
Thanks for looking into it and best regards,
Janis 

Erro ao acessar: https://global.hoymiles.com/platform/api/gateway/pvm-data/data_count_station_real_data
status_code: 400 Bad Request
I can't connect!
dados_solar: False
Traceback (most recent call last):
  File "/data/../hoymiles.py", line 653, in <module>
    pegaDadosSolar()
  File "/data/../hoymiles.py", line 548, in pegaDadosSolar
    gDadosSolar = dados_solar['data']
TypeError: 'bool' object is not subscriptable
[cmd] /run.sh exited 1

**Comment by tonwelle** [comment]
Nevermind, found the id in the hoymiles url. 👍
